### ISSUE TITLE
Большие числа не вмещаются

### ISSUE THREAD

**Issue by a-poluhin** [Constantine-P/FSD-Frontend-4-task#1]
![image](https://user-images.githubusercontent.com/10168007/76726866-00cd7e80-6785-11ea-92ba-07fcdf265ce2.png)

**Comment by Constantine-P** [comment]
Это два числа друг на друге. Я вчера-сегодня обновил это задание, переделал всю архитектуру (не думал, что так быстро с версткой закончим) и немного дизайн. Обнови у себя, пожалуйста

**Comment by Constantine-P** [comment]
100000 и 99900. Какого-то механизма скрытия или сдвигания чисел при наложении я не предусматривал, оставил на волю пользователя слайдера.

**Comment by a-poluhin** [comment]
Ага понял. Крутяк=) Сразу отпало кучка замечаний)

**Comment by a-poluhin** [comment]
Но все же поправишь наложение=)
