### ISSUE TITLE
Наименование приватных методов, переменных.

### ISSUE THREAD

**Issue by a-poluhin** [Constantine-P/FSD-Frontend-4-task#2]
![image](https://user-images.githubusercontent.com/10168007/76737057-a93a0d80-679a-11ea-96c3-c80f1876bb20.png)
Убрать нижнее подчеркивание в наименованиях.

**Comment by Constantine-P** [comment]
Тут нижнее подчеркивание потому, что имя без него уже занято геттером / сеттером. Переименовать на minValue, scaleStepsValue?

**Comment by a-poluhin** [comment]
Да у нас просто есть прям правило.
![image](https://user-images.githubusercontent.com/10168007/76740075-db01a300-679f-11ea-86c7-eebcec1b99b0.png)
